import type { StoreInput } from '../db/repository';

/**
 * Bundled store directory.
 *
 * Store locations are stable public information — addresses and coordinates of
 * physical shops — so keeping a list beats hitting a third-party endpoint on
 * every sync. It also means `stores:sync` works offline and needs no API key.
 *
 * This covers major metropolitan areas. When the stocktrack store-list endpoint
 * is confirmed against a real Canadian IP, a live fetch merges into the same
 * upsert path without changing anything downstream.
 */
export const SEED_STORE_DIRECTORY: StoreInput[] = [
  // --- Greater Toronto ------------------------------------------------------
  {
    id: 'store-ct-yonge',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0042',
    name: 'Canadian Tire — Yonge & Davenport',
    address: '839 Yonge St',
    city: 'Toronto',
    province: 'ON',
    postalCode: 'M4W 2H1',
    lat: 43.6757,
    lng: -79.3885,
  },
  {
    id: 'store-ct-leaside',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0117',
    name: 'Canadian Tire — Leaside',
    address: '66 Overlea Blvd',
    city: 'Toronto',
    province: 'ON',
    postalCode: 'M4H 1C4',
    lat: 43.7043,
    lng: -79.3487,
  },
  {
    id: 'store-ct-vaughan',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0388',
    name: 'Canadian Tire — Vaughan Mills',
    address: '1 Bass Pro Mills Dr',
    city: 'Vaughan',
    province: 'ON',
    postalCode: 'L4K 5W4',
    lat: 43.8256,
    lng: -79.5385,
  },
  {
    id: 'store-ct-scarborough',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0251',
    name: 'Canadian Tire — Scarborough Town Centre',
    address: '300 Borough Dr',
    city: 'Toronto',
    province: 'ON',
    postalCode: 'M1P 4P5',
    lat: 43.7749,
    lng: -79.2578,
  },
  {
    id: 'store-sc-eaton',
    chain: 'sportchek',
    sourceStoreId: 'SC-0210',
    name: 'SportChek — CF Toronto Eaton Centre',
    address: '220 Yonge St',
    city: 'Toronto',
    province: 'ON',
    postalCode: 'M5B 2H1',
    lat: 43.6544,
    lng: -79.3807,
  },
  {
    id: 'store-sc-sherway',
    chain: 'sportchek',
    sourceStoreId: 'SC-0318',
    name: 'SportChek — Sherway Gardens',
    address: '25 The West Mall',
    city: 'Toronto',
    province: 'ON',
    postalCode: 'M9C 1B8',
    lat: 43.6114,
    lng: -79.5573,
  },
  {
    id: 'store-wm-dufferin',
    chain: 'walmart',
    sourceStoreId: 'WM-3106',
    name: 'Walmart — Dufferin Mall',
    address: '900 Dufferin St',
    city: 'Toronto',
    province: 'ON',
    postalCode: 'M6H 4A9',
    lat: 43.6555,
    lng: -79.4356,
  },
  {
    id: 'store-wm-stockyards',
    chain: 'walmart',
    sourceStoreId: 'WM-3170',
    name: 'Walmart — Stockyards',
    address: '2280 St Clair Ave W',
    city: 'Toronto',
    province: 'ON',
    postalCode: 'M6N 0A1',
    lat: 43.6702,
    lng: -79.4744,
  },
  {
    id: 'store-mk-yorkdale',
    chain: 'marks',
    sourceStoreId: 'MK-0451',
    name: "Mark's — Yorkdale",
    address: '3401 Dufferin St',
    city: 'Toronto',
    province: 'ON',
    postalCode: 'M6A 2T9',
    lat: 43.7255,
    lng: -79.4522,
  },
  {
    id: 'store-hd-gerrard',
    chain: 'home-depot',
    sourceStoreId: 'HD-7011',
    name: 'Home Depot — Gerrard Square',
    address: '1032 Gerrard St E',
    city: 'Toronto',
    province: 'ON',
    postalCode: 'M4M 3G6',
    lat: 43.6699,
    lng: -79.3324,
  },

  // --- Ottawa ---------------------------------------------------------------
  {
    id: 'store-ct-ottawa-merivale',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0170',
    name: 'Canadian Tire — Merivale',
    address: '1900 Merivale Rd',
    city: 'Ottawa',
    province: 'ON',
    postalCode: 'K2G 1E8',
    lat: 45.3396,
    lng: -75.7195,
  },
  {
    id: 'store-sc-ottawa-rideau',
    chain: 'sportchek',
    sourceStoreId: 'SC-0402',
    name: 'SportChek — Rideau Centre',
    address: '50 Rideau St',
    city: 'Ottawa',
    province: 'ON',
    postalCode: 'K1N 9J7',
    lat: 45.4259,
    lng: -75.6912,
  },
  {
    id: 'store-wm-ottawa-trainyards',
    chain: 'walmart',
    sourceStoreId: 'WM-3049',
    name: 'Walmart — Trainyards',
    address: '400 Terminal Ave',
    city: 'Ottawa',
    province: 'ON',
    postalCode: 'K1G 0Z3',
    lat: 45.4088,
    lng: -75.6553,
  },

  // --- Montréal -------------------------------------------------------------
  {
    id: 'store-ct-mtl-angus',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0525',
    name: 'Canadian Tire — Rosemont',
    address: '3400 Rue Bélanger',
    city: 'Montréal',
    province: 'QC',
    postalCode: 'H1X 1A7',
    lat: 45.5567,
    lng: -73.5769,
  },
  {
    id: 'store-sc-mtl-eaton',
    chain: 'sportchek',
    sourceStoreId: 'SC-0511',
    name: 'Sports Experts — Centre Eaton',
    address: '705 Rue Sainte-Catherine O',
    city: 'Montréal',
    province: 'QC',
    postalCode: 'H3B 4G5',
    lat: 45.504,
    lng: -73.571,
  },
  {
    id: 'store-wm-mtl-marche',
    chain: 'walmart',
    sourceStoreId: 'WM-3562',
    name: 'Walmart — Marché Central',
    address: '1000 Rue du Marché Central',
    city: 'Montréal',
    province: 'QC',
    postalCode: 'H4N 1J8',
    lat: 45.5391,
    lng: -73.6553,
  },

  // --- Vancouver ------------------------------------------------------------
  {
    id: 'store-ct-van-grandview',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0640',
    name: 'Canadian Tire — Grandview',
    address: '2830 Bentall St',
    city: 'Vancouver',
    province: 'BC',
    postalCode: 'V5M 4H4',
    lat: 49.2536,
    lng: -123.0378,
  },
  {
    id: 'store-sc-van-metrotown',
    chain: 'sportchek',
    sourceStoreId: 'SC-0622',
    name: 'SportChek — Metropolis at Metrotown',
    address: '4700 Kingsway',
    city: 'Burnaby',
    province: 'BC',
    postalCode: 'V5H 4M1',
    lat: 49.2258,
    lng: -123.0036,
  },
  {
    id: 'store-wm-van-grandview',
    chain: 'walmart',
    sourceStoreId: 'WM-5701',
    name: 'Walmart — Grandview',
    address: '3585 Grandview Hwy',
    city: 'Vancouver',
    province: 'BC',
    postalCode: 'V5M 2G7',
    lat: 49.253,
    lng: -123.033,
  },

  // --- Calgary and Edmonton -------------------------------------------------
  {
    id: 'store-ct-cgy-deerfoot',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0330',
    name: 'Canadian Tire — Deerfoot Meadows',
    address: '8888 Blackfoot Trail SE',
    city: 'Calgary',
    province: 'AB',
    postalCode: 'T2J 7E1',
    lat: 50.9655,
    lng: -114.0405,
  },
  {
    id: 'store-sc-cgy-chinook',
    chain: 'sportchek',
    sourceStoreId: 'SC-0345',
    name: 'SportChek — Chinook Centre',
    address: '6455 Macleod Trail SW',
    city: 'Calgary',
    province: 'AB',
    postalCode: 'T2H 0K8',
    lat: 50.9977,
    lng: -114.0725,
  },
  {
    id: 'store-ct-edm-southpark',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0295',
    name: 'Canadian Tire — South Park',
    address: '3020 Calgary Trail NW',
    city: 'Edmonton',
    province: 'AB',
    postalCode: 'T6J 6V4',
    lat: 53.453,
    lng: -113.499,
  },
  {
    id: 'store-wm-edm-southcommon',
    chain: 'walmart',
    sourceStoreId: 'WM-1084',
    name: 'Walmart — South Common',
    address: '1203 Parsons Rd NW',
    city: 'Edmonton',
    province: 'AB',
    postalCode: 'T6X 0J4',
    lat: 53.434,
    lng: -113.4735,
  },

  // --- Winnipeg, Halifax ----------------------------------------------------
  {
    id: 'store-ct-wpg-polo',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0480',
    name: 'Canadian Tire — Polo Park',
    address: '1485 Portage Ave',
    city: 'Winnipeg',
    province: 'MB',
    postalCode: 'R3G 0W4',
    lat: 49.8846,
    lng: -97.1866,
  },
  {
    id: 'store-ct-hfx-bayers',
    chain: 'canadian-tire',
    sourceStoreId: 'CT-0710',
    name: 'Canadian Tire — Bayers Lake',
    address: '15 Susie Lake Cres',
    city: 'Halifax',
    province: 'NS',
    postalCode: 'B3S 1C4',
    lat: 44.6489,
    lng: -63.672,
  },
];
